update Bitrise CI yml file

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -22,6 +22,32 @@ workflows:
 
             pod lib lint CleverTap-iOS-SDK.podspec
     - script@1:
+        title: Build via Carthage
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            echo "github \"CleverTap/clevertap-ios-sdk\"" > Cartfile
+
+            carthage update
+
+            xcodebuild
+    - script@1:
+        title: Run Unit Tests
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            xcodebuild test -project CleverTapSDK.xcodeproj/ -scheme CleverTapSDKTests -destination 'name=iPhone 11'
+    - script@1:
         inputs:
         - content: |-
             #!/usr/bin/env bash
@@ -36,6 +62,17 @@ workflows:
 
             xcodebuild -workspace "ObjCStarter.xcworkspace" -scheme "ObjCStarter" -sdk iphonesimulator -destination 'name=iPhone 11' build
         title: Build ObjCStarter
+    - script@1:
+        title: Upload to Codecov
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            bash <(curl -s https://codecov.io/bash) -t c687ce9c-af35-4cc6-b31e-5d4e7d39e840
     - deploy-to-bitrise-io@1: {}
 app:
   envs:
